root: true
parser: 'babel-eslint'
parserOptions:
  sourceType: 'module'
env:
  browser: true
extends: standard
plugins:
  - html
rules:
  indent: ["error", 2, { "MemberExpression": off, "SwitchCase": 1}]
  no-mixed-operators: 0
  object-curly-spacing: [2, 'always', { objectsInObjects: false }]
  standard/object-curly-even-spacing: 0
